paths:
  /mission/progress:
    post:
      tags:
        - OnProgress
      summary: 미션 진행중에 추가
      parameters:
      - name: addMissionOnProgress
        in: body
        required: true
        schema:
          properties:
            member_id:
              type: bigint
              description: 사용자 id
              example: 1
            mission_id:
              type: bigint
              description: 미션 id
              example: 1
      responses:
        '200':
          description: 미션 진행중 추가 성공!
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 200
              isSuccess:
                type: boolean
                example: true
              code:
                type: integer
                example: 2000
              message:
                type: string
                example: "success!"
              data:
                type: object
              example: 
                "progress_status": "진행중"
                
        '400':
          description: 잘못된 요청
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 400
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON001
              message:
                type: string
                example: 잘못된 요청입니다

        '500':
          description: 서버 에러
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 500
              isSuccess:
                type: boolean
                example: false
              code:
                type: integer
                example: COMMON000
              message:
                type: string
                example: 서버 에러, 관리자에게 문의 바랍니다.